// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FlashMessagesController from "./flash_messages_controller"
application.register("flash-messages", FlashMessagesController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ProgressBarController from "./progress_bar_controller"
application.register("progress-bar", ProgressBarController)

import ProgressController from "./progress_controller"
application.register("progress", ProgressController)
