// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BootstrapController from "./bootstrap_controller"
application.register("bootstrap", BootstrapController)

import BsModalController from "./bs_modal_controller"
application.register("bs-modal", BsModalController)

import FlashMessagesController from "./flash_messages_controller"
application.register("flash-messages", FlashMessagesController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ProgressController from "./progress_controller"
application.register("progress", ProgressController)
